apiVersion: apps/v1
kind: Deployment
metadata:
  name:  expiration-depl
  namespace: default
  labels:
    app:  expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration-depl
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  expiration-depl
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  expiration-depl
        image: moacrnorth.azurecr.io/ticketing/expiration
        imagePullPolicy: Always
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-svc:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing        
          - name: REDIS_HOST
            value: expiration-redis-svc
