apiVersion: apps/v1
kind: Deployment
metadata:
  name:  orders-depl
  namespace: default
  labels:
    app:  orders-depl
spec:
  selector:
    matchLabels:
      app: orders-depl
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  orders-depl
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  orders-depl
        image: moacrnorth.azurecr.io/ticketing/orders
        imagePullPolicy: Always
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-svc:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing        
          - name: MONGO_URI
            value: 'mongodb://orders-mongo-svc:27017/orders'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  namespace: default
spec:
  selector:
    app: orders-depl
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: orders-depl-3000
    protocol: TCP
    port: 3000
    targetPort: 3000
