apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payments-depl
  namespace: default
  labels:
    app:  payments-depl
spec:
  selector:
    matchLabels:
      app: payments-depl
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  payments-depl
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  payments-depl
        image: moacrnorth.azurecr.io/ticketing/payments
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-svc:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing        
          - name: MONGO_URI
            value: 'mongodb://payments-mongo-svc:27017/payments'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-secret
                key: STRIPE_KEY                
---
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
  namespace: default
spec:
  selector:
    app: payments-depl
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: payments-depl-3000
    protocol: TCP
    port: 3000
    targetPort: 3000
