name: deploy-auth

on:
  push:
    branches: ["master"]
    paths:
      - 'auth/**'


jobs:
  buildImage:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          repository: ticketing
          image: auth