name: deploy-auth

on:
  push:
    branches: ["master"]
    paths:
      - 'auth/**'


jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$CONTAINER_NAME --registry AZURE_CONTAINER_REGISTRY -g RESOURCE_GROUP .
         env: 
          AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          CONTAINER_NAME: auth
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
